### ISSUE TITLE
capturing Unhandled exceptions

### ISSUE THREAD

**Issue by SandipFichadiya** [toddanglin/nativescript-trace-raven#2]
Hello, how can I capture Unhandled exceptions? I have tried by doing this but it's not working

```
app.on(app.uncaughtErrorEvent, function (args) {
    if (args.android) {
        console.log("args>android => " + args.android);
        console.log("args>android>native => " + args.android.nativeException);
        console.log("args>android>stackTrace => " + args.android.stackTrace);
        Raven.captureException(args);

    } else if (args.ios) {
        Raven.captureException(args);
    }
});
```
am I missing something here?

**Comment by toddanglin** [comment]
So I took a look at this scenario...and it should be working.

Obviously, make sure you've initialized the plugin properly and that you include the Raven library in your app.js/.ts file:

```
import Raven = require("raven-js");
```

The only thing you need to change is this the value you're sending to Sentry. Instead of sending the entire `args` value, send the platform specific NativeScriptError object. For example:

```
Raven.captureException(args.ios);
```

This will transmit the device details plus the error that caused the unhandled exception. It is NOT today sending the full stack trace, though. Will have to investigate further to see how to get that included. It might work by simply passing the `args.ios.stackTrace` to the `captureException` method.

I've also observed that the `uncaughtErrorEvent` does not work in the iOS simulator. So to test this, I think you must use a real device. Not 100% certain, but trying to verify with {N} team.

Hope this helps.

**Comment by AsrarMemon** [comment]
hello,

i am doing same thing which is mention you 

import : 
```
import * as app from 'application';
import * as trace from 'trace';
 import { TraceRaven } from 'nativescript-trace-raven';
 import Raven = require("raven-js");
```
code:
```
app.on(app.uncaughtErrorEvent, function (args) {
    if (args.android) {
        console.log("args>android => " + args.android);
        console.log("args>android>native => " + args.android.nativeException);
        console.log("args>android>stackTrace => " + args.android.stackTrace);
        Raven.captureException(args.android.stackTrace);

    } else if (args.ios) {
        Raven.captureException(args.ios.stackTrace);
    }
});
```
still not working..
am I missing something here?

**Comment by toddanglin** [comment]
Can you provide any detail on the error you’re getting? Error message? Platform?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
